import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, CalendarDays, ChevronRight, ClipboardPlus, HeartPulse, House, MapPin, PawPrint, Plus, Search, Settings, Stethoscope, Weight } from 'lucide-react';
import './styles.css';

type Pet = { id: number; name: string; species: string; breed: string; sex: string; birth: string; weight: number; allergies: string; color: string };
type Reminder = { id: number; pet: string; title: string; due: string; type: string };
type Appointment = { id: number; pet: string; provider: string; service: string; date: string; status: 'Confirmada' | 'Pendiente' };
const initialPets: Pet[] = [
  { id: 1, name: 'Milo', species: 'Perro', breed: 'Labrador Retriever', sex: 'Macho', birth: '2021-04-12', weight: 29.4, allergies: 'Pollo', color: 'Dorado' },
  { id: 2, name: 'Luna', species: 'Gato', breed: 'Europeo común', sex: 'Hembra', birth: '2023-08-21', weight: 4.2, allergies: 'Sin alergias registradas', color: 'Gris atigrado' }
];
const initialReminders: Reminder[] = [
  { id: 1, pet: 'Milo', title: 'Vacuna antirrábica', due: '2026-07-20', type: 'Vacuna' },
  { id: 2, pet: 'Luna', title: 'Antiparasitario interno', due: '2026-07-23', type: 'Salud' },
  { id: 3, pet: 'Milo', title: 'Control de peso', due: '2026-07-30', type: 'Control' }
];
const initialAppointments: Appointment[] = [{ id: 1, pet: 'Milo', provider: 'Clínica Vet Andes', service: 'Control anual', date: '2026-07-20T10:30', status: 'Confirmada' }];
function stored<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key) || '') as T; } catch { return fallback; } }
function App() {
  const [section, setSection] = useState('Inicio'); const [pets, setPets] = useState(() => stored('petcare.pets', initialPets));
  const [reminders, setReminders] = useState(() => stored('petcare.reminders', initialReminders)); const [appointments, setAppointments] = useState(() => stored('petcare.appointments', initialAppointments));
  const [dark, setDark] = useState(false); const [modal, setModal] = useState<'pet'|'appointment'|null>(null); const [selected, setSelected] = useState<Pet | null>(pets[0]);
  useEffect(() => { localStorage.setItem('petcare.pets', JSON.stringify(pets)); }, [pets]); useEffect(() => { localStorage.setItem('petcare.reminders', JSON.stringify(reminders)); }, [reminders]); useEffect(() => { localStorage.setItem('petcare.appointments', JSON.stringify(appointments)); }, [appointments]);
  const nav = [{ label:'Inicio', icon: House }, { label:'Mis mascotas', icon:PawPrint }, { label:'Salud', icon:HeartPulse }, { label:'Calendario', icon:CalendarDays }, { label:'Agenda', icon:ClipboardPlus }, { label:'Directorio', icon:MapPin }];
  const due = useMemo(() => reminders.slice().sort((a,b) => a.due.localeCompare(b.due)), [reminders]);
  const addPet = (data: FormData) => { const pet: Pet = { id: Date.now(), name: String(data.get('name')), species:String(data.get('species')), breed:String(data.get('breed')), sex:String(data.get('sex')), birth:String(data.get('birth')), weight:Number(data.get('weight')), allergies:String(data.get('allergies') || 'Sin alergias registradas'), color:String(data.get('color')) }; setPets([...pets,pet]); setSelected(pet); setModal(null); setSection('Mis mascotas'); };
  const addAppointment = (data: FormData) => { setAppointments([...appointments, { id: Date.now(), pet:String(data.get('pet')), provider:String(data.get('provider')), service:String(data.get('service')), date:String(data.get('date')), status:'Pendiente' }]); setModal(null); setSection('Agenda'); };
  return <div className={dark ? 'app dark' : 'app'}><aside><div className="brand"><PawPrint/> <span>PET<span>CARE</span></span></div><p className="workspace">MI ESPACIO</p>{nav.map(({label,icon:Icon}) => <button className={section===label?'nav active':'nav'} onClick={()=>setSection(label)} key={label}><Icon size={19}/>{label}</button>)}<div className="aside-bottom"><button className="nav"><Settings size={19}/>Configuración</button><button className="profile"><span>CM</span><b>Carolina Morales<small>Dueña de mascotas</small></b><ChevronRight size={16}/></button></div></aside>
    <main><header><div><p className="eyebrow">JUEVES, 16 DE JULIO</p><h1>{section === 'Inicio' ? 'Buenos días, Carolina' : section}</h1></div><div className="header-actions"><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Cambiar tema">◐</button><button className="icon-button"><Bell size={19}/><i/></button><button className="add" onClick={()=>setModal(section==='Agenda'?'appointment':'pet')}><Plus size={18}/>Nueva {section==='Agenda'?'reserva':'mascota'}</button></div></header>
      {section==='Inicio' && <Dashboard pets={pets} due={due} appointments={appointments} onNavigate={setSection} />}
      {section==='Mis mascotas' && <Pets pets={pets} selected={selected} setSelected={setSelected} onAdd={()=>setModal('pet')} />}
      {section==='Salud' && <Health pet={selected || pets[0]} reminders={reminders} setReminders={setReminders} />}
      {section==='Calendario' && <Calendar reminders={due} />}
      {section==='Agenda' && <Agenda appointments={appointments} onAdd={()=>setModal('appointment')} />}
      {section==='Directorio' && <Directory />}
    </main>{modal==='pet' && <Modal title="Registrar mascota" close={()=>setModal(null)}><form action={addPet}><Field name="name" label="Nombre" required/><div className="form-grid"><Field name="species" label="Especie" required/><Field name="breed" label="Raza" required/></div><div className="form-grid"><Select name="sex" label="Sexo" values={['Macho','Hembra']}/><Field name="birth" label="Fecha de nacimiento" type="date" required/></div><div className="form-grid"><Field name="weight" label="Peso (kg)" type="number" required/><Field name="color" label="Color" required/></div><Field name="allergies" label="Alergias"/><button className="submit">Guardar mascota</button></form></Modal>}{modal==='appointment' && <Modal title="Nueva reserva" close={()=>setModal(null)}><form action={addAppointment}><Select name="pet" label="Mascota" values={pets.map(p=>p.name)}/><Field name="provider" label="Centro o profesional" required/><Field name="service" label="Servicio" required/><Field name="date" label="Fecha y hora" type="datetime-local" required/><button className="submit">Solicitar reserva</button></form></Modal>}</div>;
}
function Dashboard({pets,due,appointments,onNavigate}:{pets:Pet[];due:Reminder[];appointments:Appointment[];onNavigate:(x:string)=>void}) { return <><section className="hero"><div><p>Todo el bienestar de tu familia peluda, en un solo lugar.</p><button onClick={()=>onNavigate('Mis mascotas')}>Ver mis mascotas <ChevronRight size={17}/></button></div><div className="hero-paws">🐾</div></section><section className="metrics"><Metric icon={<PawPrint/>} number={pets.length} label="Mascotas registradas"/><Metric icon={<Bell/>} number={due.length} label="Recordatorios activos"/><Metric icon={<CalendarDays/>} number={appointments.length} label="Próximas reservas"/></section><div className="grid"><section className="card"><div className="section-head"><div><h2>Próximos cuidados</h2><p>Planifica el bienestar de tus mascotas</p></div><button className="link" onClick={()=>onNavigate('Calendario')}>Ver calendario</button></div>{due.map(item=><div className="reminder" key={item.id}><span className="reminder-dot">{item.type==='Vacuna'?'✚':'●'}</span><div><b>{item.title}</b><p>{item.pet} · {new Date(item.due+'T12:00').toLocaleDateString('es-CL',{day:'numeric',month:'long'})}</p></div><ChevronRight size={18}/></div>)}</section><section className="card"><div className="section-head"><div><h2>Mis mascotas</h2><p>Acceso rápido a sus fichas</p></div><button className="link" onClick={()=>onNavigate('Mis mascotas')}>Ver todas</button></div><div className="pet-cards">{pets.map((pet,i)=><div className="pet-card" key={pet.id}><div className={'pet-avatar p'+i}>{pet.species==='Gato'?'🐱':'🐶'}</div><b>{pet.name}</b><small>{pet.breed}</small><span>{pet.weight} kg</span></div>)}</div></section></div></> }
const Metric=({icon,number,label}:{icon:React.ReactNode;number:number;label:string})=><div className="metric"><span>{icon}</span><div><strong>{number}</strong><p>{label}</p></div></div>;
function Pets({pets,selected,setSelected,onAdd}:{pets:Pet[];selected:Pet|null;setSelected:(p:Pet)=>void;onAdd:()=>void}) { const p=selected || pets[0]; return <div className="pets-layout"><section className="card pet-list"><div className="section-head"><h2>Familia</h2><button className="round" onClick={onAdd}><Plus size={18}/></button></div>{pets.map((pet,i)=><button key={pet.id} className={p.id===pet.id?'pet-row selected':'pet-row'} onClick={()=>setSelected(pet)}><span className={'mini p'+i}>{pet.species==='Gato'?'🐱':'🐶'}</span><span><b>{pet.name}</b><small>{pet.species} · {pet.breed}</small></span></button>)}</section><section className="card record"><div className="record-banner"><span className="big-pet">{p.species==='Gato'?'🐱':'🐶'}</span><div><p>FICHA DE MASCOTA</p><h2>{p.name}</h2><span>{p.species} · {p.breed}</span></div></div><h3>Información general</h3><div className="facts"><Fact title="Sexo" value={p.sex}/><Fact title="Nacimiento" value={new Date(p.birth+'T12:00').toLocaleDateString('es-CL')}/><Fact title="Peso actual" value={`${p.weight} kg`}/><Fact title="Color" value={p.color}/><Fact title="Alergias" value={p.allergies}/><Fact title="Estado" value="Activo"/></div><h3>Acciones clínicas</h3><div className="quick-actions"><button><Stethoscope/>Nueva consulta</button><button><Weight/>Registrar peso</button><button><CalendarDays/>Agendar atención</button></div></section></div> }
const Fact=({title,value}:{title:string;value:string})=><div><small>{title}</small><b>{value}</b></div>;
function Health({pet,reminders,setReminders}:{pet:Pet;reminders:Reminder[];setReminders:(x:Reminder[])=>void}) { const [item,setItem]=useState(''); const add=()=>{if(item.trim()){setReminders([...reminders,{id:Date.now(),pet:pet.name,title:item,due:new Date().toISOString().slice(0,10),type:'Salud'}]);setItem('')}};return <div className="content-narrow"><section className="card health-card"><p className="eyebrow">HISTORIAL CLÍNICO</p><h2>{pet.name}</h2><div className="health-tabs"><button className="tab active">Resumen</button><button className="tab">Vacunas</button><button className="tab">Medicamentos</button><button className="tab">Documentos</button></div><div className="timeline"><div><span>16 JUL</span><article><b>Control de bienestar</b><p>Sin novedades clínicas. Peso registrado: {pet.weight} kg.</p></article></div><div><span>08 JUN</span><article><b>Desparasitación interna</b><p>Tratamiento registrado correctamente.</p></article></div></div><div className="add-reminder"><input value={item} onChange={e=>setItem(e.target.value)} placeholder="Agregar nota clínica o cuidado"/><button onClick={add}>Registrar</button></div></section></div> }
function Calendar({reminders}:{reminders:Reminder[]}) {return <section className="card calendar"><div className="section-head"><div><p className="eyebrow">JULIO 2026</p><h2>Calendario sanitario</h2></div><button className="add">Configurar alertas</button></div><div className="calendar-grid">{Array.from({length:31},(_,i)=>{const day=i+1;const ev=reminders.filter(r=>Number(r.due.slice(-2))===day);return <div className={ev.length?'date has-event':'date'} key={day}><b>{day}</b>{ev.map(x=><span key={x.id}>{x.pet}: {x.title}</span>)}</div>})}</div></section>}
function Agenda({appointments,onAdd}:{appointments:Appointment[];onAdd:()=>void}) {return <section className="card"><div className="section-head"><div><p className="eyebrow">ATENCIONES</p><h2>Próximas reservas</h2></div><button className="add" onClick={onAdd}><Plus size={17}/>Reservar hora</button></div>{appointments.map(a=><article className="appointment" key={a.id}><div className="date-box"><b>{new Date(a.date).getDate()}</b><span>{new Date(a.date).toLocaleDateString('es-CL',{month:'short'}).replace('.','')}</span></div><div><h3>{a.service}</h3><p>{a.pet} · {a.provider}</p><small>{new Date(a.date).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}</small></div><span className={'status '+a.status.toLowerCase()}>{a.status}</span></article>)}</section>}
function Directory(){const places=['Clínica Vet Andes · 1.2 km','Hospital Veterinario Central · 2.8 km','Peluquería Patitas · 3.1 km','Farmacia Animal · 3.6 km'];return <div className="directory"><section className="map"><MapPin size={34}/><h2>Servicios cerca de ti</h2><p>Activa la ubicación para calcular rutas y tiempos estimados.</p><button>Usar mi ubicación</button></section><section className="card"><div className="search"><Search size={18}/><input placeholder="Buscar veterinarias, peluquerías, farmacias..."/></div>{places.map((x,i)=><div className="place" key={x}><span>{i===2?'✂':'✚'}</span><div><b>{x.split(' · ')[0]}</b><p>{x.split(' · ')[1]} · Abierto ahora</p></div><button className="link">Ver ficha</button></div>)}</section></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay"><section className="modal"><button className="close" onClick={close}>×</button><h2>{title}</h2>{children}</section></div>}; const Field=({name,label,type='text',required=false}:{name:string;label:string;type?:string;required?:boolean})=><label>{label}<input name={name} type={type} required={required}/></label>;const Select=({name,label,values}:{name:string;label:string;values:string[]})=><label>{label}<select name={name}>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
createRoot(document.getElementById('root')!).render(<App/>);
